_target_: include.generators.InvUncertaintyGen
shuffle: True
no2_plume_scaling_min: 0.75
no2_plume_scaling_max: 2
xco2_emiss_min: 0
xco2_emiss_max: 45
scaling_method: beta_distribution_mapping
batch_size: ${training.batch_size}
path_inv_model: /libre/dumontj/coco2/weights/new/inv_lip_test_32_sweep/4
